#ifndef CONSTANTS_H
#define CONSTANTS_H

class Constants
{
const int SCREEN_WIDTH = 1200/2;
const int SCREEN_HEIGHT = 1200/2;

const int FIGURE_TEXTURE_WIDTH = 1800;
const int FIGURE_TEXTURE_HEIGHT = 800;

const int FIGURE_WIDTH = FIGURE_TEXTURE_WIDTH/6;
const int FIGURE_HEIGHT = FIGURE_TEXTURE_HEIGHT/2;

const int CHESS_TEXTURE_WIDTH = 1200/2;
const int CHESS_TEXTURE_HEIGHT = 1200/2;

const int CHESSB_WIDTH = CHESS_TEXTURE_WIDTH/8;
const int CHESSB_HEIGHT = CHESS_TEXTURE_HEIGHT/8;
};

#endif // CONSTANTS_H
